@startuml dispatch-engine-assign-drivers-sequence

skinparam monochrome true
skinparam responseMessageBelowArrow true

title Dispatch Engine - Assign Drivers

' participants
' ------------

participant "Dispatch Orchestrator" as dispatchOrchestrator
participant "Dispatcher Resource" as dispatcherResource
participant "Dispatcher Service" as service
participant "Solver Manager" as solverManager
participant "Driver Query Manager" as driverQueryManager
participant "GraphHopper" as gh
participant "DynamoDB" as ddb

== Handle incoming orders ==

    dispatchOrchestrator -> dispatcherResource : **POST**\n///instant/sequential/dispatch/assign-drivers//
    dispatcherResource -> dispatcherResource : //UUID.random()//

    dispatcherResource -> service : //solverJob::enqueue//
    dispatcherResource --> dispatchOrchestrator : //uuid//

    service -> driverQueryManager : //retrieveDrivers(locations)//
    driverQueryManager --> service : //drivers//

    service -> ddb : //assignment(ENQUEUED)//

    service -> gh : //genDistanceMatrix(drivers,origins,destinations)//
    gh --> service : //distanceMatrix//

    service -> solverManager : //dispatchingProblem//
    service -> ddb : //assignment(SOLVING_SCHEDULED)//

    solverManager -> solverManager : solve
    solverManager --> service : //bestSolution//

    service -> ddb : //assignment(NOT_SOLVING)//

@enduml